### ISSUE TITLE
MinimumSegmentLength does not work (anymore)

### ISSUE THREAD

**Issue by rune83** [oxyplot/oxyplot#1044]
### Steps to reproduce

1. Create and display a big dataset as lineseries
2. Increase the value of "MinimumSegmentLength" to e.g. 10 
3. ->no changes in the chart regarding rendering speed and form of the signal

Platform: Windows (WPF project)
.NET version: 4.5

**MinimumSegmentLength should reduce/skip datapoints in lineseries when using big datasets.
This speeds up the rendering.**

### Expected behaviour
It speeds up the rendering and spoils the signal a little. 
It worked in oxyplot versions bevor the "stable 1.0" version.

### Actual behaviour
Since the stable version 1.0 it did not work anymore, also not on the current beta build. 
Changes in value won't affect speed and rendering of the lines.

_I have the theory that the bug was introduced by bugfix #913 .._

**Comment by Jonarw** [comment]
It seems indeed that this was introduced by #913 . The `minDistSquared` is only implemented in the old render path, which is only used when the `RenderContext` returns `false` when calling `SetClip(...)`. I am not even sure if there is a renderer that does this; in any case this is broken for most renderers.

The obvious fix would be to add this functionality also for the new render path. Ideally as a separate function along the lines of 
`IEnumerable<ScreenPoint> ReducePoints(IReadOnlyList<ScreenPoint> points, double minDistSquared)`
so `DrawClippedPolygon(...)` could also benefit from this.

This function could also address #1054 , which is also broken at the moment because it is only implemented for the old render path.

I will look into this a bit more during the next days. If there is some additional input, please let me know.

**Comment by Jonarw** [comment]
So I looked into this a bit more. `MinimumSegmentLength` is easily fixable in `RenderingExtensions`.

#1054 is a bit of a different problem. I don't really like the approach to artificially expand isolated points on render level to make them visible. I think this should not happen on render level, rather the series itself should be responsible for if and how isolated points are visualized. For example one could add properties `IsolatedPointsMarker` and `IsolatedPointsMarkerSize` to `LineSeries` to visualize isolated points. However I think this out of the scope of this issue.

Therefore I would propose the following actions for this issue:
- Fix `MinimumSegmentLength` for new render path as outlined in my previous comment
- Make old and new render path consistent by essentially removing `EnsureNonEmptyLineIsVisible(...)` in `RenderingExtensions`
- Adapt unit tests for `RenderingExtensions` accordingly

This will fix #913. It will not fix #1054, but will at least make it equally broken for old and new render path. To fix #1054 we could, in a separate PR, add back in some kind of capability for rendering isolated points, possibly as outlined above.

Any thoughts on this?

---

For clarification, this is what I mean by 'new' and 'old' render path:
['New' render path](https://github.com/oxyplot/oxyplot/blob/develop/Source/OxyPlot/Rendering/RenderContext/RenderingExtensions.cs#L96)
['Old' render path](https://github.com/oxyplot/oxyplot/blob/develop/Source/OxyPlot/Rendering/RenderContext/RenderingExtensions.cs#L115)

**Comment by objorke** [comment]
Thanks for good ideas, @jonarw! I tried to implement this as you suggested (but not looking into #1054 here)
