### ISSUE TITLE
End support for Silverlight

### ISSUE THREAD

**Issue by objorke** [oxyplot/oxyplot#1049]
Make the releases easier.
In my opinion it is too cumbersome to develop and test Silverlight these days. (need to install an SDK, and installing the SDK never works on my machine).

Silverlight is supported until 2021...

**Comment by AlexeiScherbakov** [comment]
1. Chromium browsers are not supporting Silverlight [since September 2015](https://blog.chromium.org/2014/11/the-final-countdown-for-npapi.html)
2. Silverlight for Windows Phone is superseded by UWP
3. Firefox not supporting Silverlight [since 52 version](https://bugzilla.mozilla.org/show_bug.cgi?id=1269807)

Silverlight is useless today

**Comment by GeertvanHorrik** [comment]
I can remove the files for this one if you want.

**Comment by objorke** [comment]
I have created https://github.com/oxyplot/oxyplot-silverlight

filtered commits with
```
git clone https://github.com/oxyplot/oxyplot.git
cd oxyplot
git remote rm origin
git filter-branch -f --prune-empty --index-filter "git rm --cached -r -q -- . ; git reset -q $GIT_COMMIT -- Source/OxyPlot/OxyPlot_SL5.csproj Source/OxyPlot.Silverlight Source/OxyPlot.Pdf Source/Examples/Silverlight Source/Examples/Mono* Source/OxyPlot.Silverlight.sln Source/AssemblyInfo.cs .gitattributes .gitignore LICENSE" -- --all
cd ..
git clone https://github.com/oxyplot/oxyplot-silverlight.git
cd oxyplot-silverlight
git remote add oxyplot ../oxyplot
git pull oxyplot develop
git remote rm oxyplot
```

@GeertvanHorrik I can remove the files
