### ISSUE TITLE
System.OverflowException occurs when zoomed in to lowest limit on logarithmic scale

### ISSUE THREAD

**Issue by sap087** [oxyplot/oxyplot#1090]
*IF BUG, INCLUDE THIS PART:*

### Steps to reproduce

1.Set Linear XAxis, AbsoluteMinimum = 0
2.Set yaxis as a Logarithmic axis
3. scroll up with mouse wheel to zoom in on both the X and Y axes.
4. Continue zooming in until an error message is displayed in the plot window:

Platform:OxyPlot.wpf
.NET version: 4.0

### Expected behaviour
No Exception occurs.

### Actual behaviour

PlotView shows System.OverflowException message.
![image](https://cloud.githubusercontent.com/assets/25901383/26102251/2bff7aba-3a2c-11e7-85c3-f1c35bb37ff5.png)

![image](https://cloud.githubusercontent.com/assets/25901383/26102381/a7d19fe2-3a2c-11e7-979c-e3b478e9c51c.png)

**Comment by shnaramn** [comment]
The issue seems to be here:
https://github.com/oxyplot/oxyplot/blob/develop/Source/OxyPlot/Axes/LogarithmicAxis.cs#L70

I'm guessing the Convert.ToInt32 is not necessary here. The fix could be as simple as using ticksPerDecade in its double form (rather than converting to int and then using it).

Or am I missing something here?

**Comment by Isolocis** [comment]
Removing Convert.ToInt32 would change the behaviour of the function, since ticksPerDecade is not an integer value. To keep the same behaviour and fix the described error we could replace Convert.ToInt32 with Math.Floor. 

I can create a PR with the issue + fix if you want.
