### ISSUE TITLE
PNG exporter based on ImageSharp

### ISSUE THREAD

**Issue by kirsis** [oxyplot/oxyplot#1188]
### Feature description

On Linux and macOS platforms, the built-in PNG exporters don't work, as they rely on native Windows APIs. 

For my own use, I have created a custom PNG exporter based on [ImageSharp](https://github.com/SixLabors/ImageSharp). As it is fully managed code, it should work on all platforms. 

It works alright for simple use cases, but it has limitations. For example - it can only draw text at 72 DPI, regardless of the desired image resolution (this is an ImageSharp limitation at the moment). However, it is better than nothing for Linux/macOS users.

The exporter was based on OxyPlot.Pdf exporter, and the rendering context can be seen here: https://gist.github.com/kirsis/f1e38def0296663dafb000acfb4099e1 

If I were to package it up in a similar project to OxyPlot.Pdf - e.g. OxyPlot.Png - except targeting netstandard2.0 and containing only this rendering context and exporter, would you accept that pull request?

**Comment by objorke** [comment]
Yes! This sounds very good. Agree it should be a separate package.

**Comment by objorke** [comment]
We have the PngExporter based on System.Drawing.Common (.NET Core). Will ImageSharp give us anything extra?

**Comment by VisualMelon** [comment]
@objorke random thoughts:
 - ImageSharp would provide 'purely-managed' cross-platform support (no need for libgdiplus etc.) so is more portable (e.g. I can't use System.Drawing.Core at work, but I can and do use ImageSharp)
 - It is also likely that ImageSharp will gain useful features over time (e.g. better/more bitmap export options (Png compression, serious Jpeg support, etc.)
 - People using ImageSharp may make use of the 'native' API (e.g. direct access to frames without the costs of having to encode and decode through a memory stream)

It's been a while since I wrote any code with ImageSharp, and I don't recall being overly impressed (it was a while back), but I'd be happy to direct my efforts toward this for the moment.
