### ISSUE TITLE
Aligning independent PlotViews

### ISSUE THREAD

**Issue by SkinnySackboy** [oxyplot/oxyplot#1200]
We've got a feature request to have multiple stacked plots - where we have been able to keep all panning/zooming etc. in sync. So far so good.

The only problem I cannot find a solution for is that depending on the label of the values on the respective y-axes, the y-axis may or may not be automatically indented to make space for the increased label widths. This means that depending on the current visible range, the plots are not always perfectly aligned. I've attached a screenshot here to explain what I mean, where the red arrow is pointing towards the indentation which is undesirable in this case. 

![image](https://user-images.githubusercontent.com/5160717/37662623-bd61f8ac-2c57-11e8-8256-ca67dc9cb968.png)

Is there a way to make sure that stacked independent plots are always drawn such that they are not sensitive to the width required to draw the axes value labels?

Thanks!

**Comment by Dunkhan** [comment]
I assume you closed this because you found a way.
If not, or for others that found this, the way I do it as follows.
Assuming your Y axis title uses the same font and has at least one upper case letter in each plot, that should not be a factor. This leaves only the axis labels with the numbers. In the example above you can see that '-0.50' is much longer than '20' and therefore takes a wider margin. This can also be an issue because if you zoom or pan these labels change, meaning the margins change size and the alignments jump around.
The way I deal with this in my plots is with the axis label formatting. I don't have the exact code in front of me right now but you can assign a format function to an axis. You then create a function which pads your axis labels with spaces to the left with a format string like "{0,6}", where 6 is the maximum length number of digits your axis is likely to have. This will pad spaces on the left side.
Apologies if this description is not helpful, I will try to dig out a concrete example next time I have it and paste that here.

**Comment by SkinnySackboy** [comment]
Thank you very much @Dunkhan this was exactly what I tried for my first attempt, though yesterday I discovered the PlotMargins property (defaulted to NaN, NaN, NaN, NaN) can be set and solves the problem I encountered perfectly. Thank you for taking the time to reply!

**Comment by Dunkhan** [comment]
If you want to set just the left margin, you can set all the others to NaN to keep the automatic margin calculation for those ones

**Comment by SkinnySackboy** [comment]
Thanks yeah literally an hour ago that's is exactly what I did :) and it works great!
