### ISSUE TITLE
Cupport for Chinese

### ISSUE THREAD

**Issue by mzy666888** [oxyplot/oxyplot#1253]
I use oxyPlot for winform, but I find this Not support for Chinese
`var model = new PlotModel()
            {
                Title = "中文"
            };`
but it not work.
### how should I do?
![image](https://user-images.githubusercontent.com/2587129/47481251-92bdaa00-d865-11e8-9a37-40a82b7f02af.png)

**Comment by gotoh** [comment]
I got similar issue in Japanese text in title or non default font/size text in axis title.
I found and using a easy workaround like the following.
  System.Drawing.StringFormat.GenericTypographic.FormatFlags &= ~StringFormatFlags.LineLimit;

It also seems to be okay if you increase the drawing area of ​​the text a little. There seems to be something severe things around that in Typographic mode.

Of course it is not good solution because it changes the global constant FormatFlags.
I home someone tackle this issue and resolve.

**Comment by qq543139310** [comment]
default font "helvetica" not support Chinese,
try font "times" and "courier".

**Comment by kwokngaiwai** [comment]
System.Drawing.StringFormat.GenericTypographic.FormatFlags &= ~StringFormatFlags.LineLimit;
var model = new PlotModel();

这么操作下好像可以了，原理还不知道.
(add line as above ,dont know why)

**Comment by mzy666888** [comment]
解决
