### ISSUE TITLE
[Help-Wanted] How to make different PlotViews aligned to each other

### ISSUE THREAD

**Issue by ShannonZ** [oxyplot/oxyplot#1277]
### Feature description
![alginsubplot](https://user-images.githubusercontent.com/7865691/52027998-52e31e80-2548-11e9-8172-c1438ed0dd87.png)

Plots are arranged as follows:

subplot(2,2,1) projection along y-axis | subplot(2,2,3)
-----------------------------------------|----------------
subplot(2,2,2) heatmap series              | subplot(2,2,4) projection along x-axis

I want to show a heatmap serie and the corresponding projections in one window. The same label font size and data range were used.  In ideal case, the x-axis of the upper chart(_subplot(2,2,1)_) should be aligned with that of the chart displaying heatmap series(_subplot(2,2,2)_). But the space occupied by coloraxis changes the situation.

How to make the x-axis of **_subplot(2,2,1)_** aligned with that of **_subplot(2,2,2)_**, and the y-axis of **_subplot(2,2,4)_** aligned with that of **_subplot(2,2,2)_**?

Demo to reproduce was attached: https://github.com/ShannonZ/playground

If this cannot be easily implemented, is it possible to merge all subplots together to make a compact plot as follows:
![_20190215094241](https://user-images.githubusercontent.com/7865691/52829231-e438c000-3106-11e9-97d2-bf5c5cda1229.jpg)

**Comment by VisualMelon** [comment]
I had a requirement like this recently; unfortunately, OxyPlot is designed to make the best use of space possible, so 'margins' between the view-space and the plot-area are dynamically computed. The only options I found were to change this behaviour in `PlotModel` (which is what I did [in this branch](https://github.com/VisualMelon/oxyplot/tree/plotmodelbounds) (discussion in #55)), or to manually adjust the margins, responsively or otherwise (e.g. in your case, [this code (gist)](https://gist.github.com/VisualMelon/66057ff78b8eb2fd8e7d8f370a5524b1) almost does the job). The residual problem with fixing margins is that the axis label positions vary according to the width of the tick labels, which can only reasonably be solved by rotating the text or formatting it so that it has a consistent width.

Thought: user-control of axis `TierSize` (presently `internal` and computed in `AdjustAxesPositions`) might make sense, and allow 'easy' bodging to sub-plots

**Comment by ShannonZ** [comment]
I achieved it by setting a proper `PlotMargin`. https://gitter.im/oxyplot/oxyplot?at=63219953f4d7a323ded0d326

**Comment by David-HH-Dev** [comment]
Hi, I came across this topic. We are using OxyPlot in our software and we are linking the plot margins of multiple graphs with each other. The goal I believe is similar to this request.
For example if we have two plots (vertically arranged) and they share the same x-values, but not the same y-values, then we want the screen coordinate of the y-axis to be the same for the upper and the lower plot.
This kind of worked in the past, by subscribing to the PlotModel.Updated event and then getting the width of the y-axis from the Axis.DesiredSize. We recently updated to OxyPlot v2.1 and this changed it to Axis.DesiredMargins, and since it's not working reliably anymore. I'm now listening to Axis.AxisChanged rather than PlotModel.Updated and it seems that it works again, but anyway all those events are marked as obsolete.
So I wonder if you came across an example where linking/aligning the axes is working and explained?
The link from @ShannonZ  doesn't really bring me to his example.

**Comment by VisualMelon** [comment]
Can you post the code you are using for syncing the margins that isn't working?

**Comment by David-HH-Dev** [comment]
@VisualMelon 
We have a WPF control (i.e. we are using OxyPlot.WPF). In this control users can arrange several plots vertically, in which the plots share the same x-axis. We achieve that by only showing the x-axis of the bottommost plot and not of the others and linking the zoom. Then in this control we have several triggers that would "calculate" the width of the widest y-axis and apply that as plot margin to all plots (same for a secondary y-axis which is located on the right side, but this is less of a priority). The triggers we are using to refresh the plot margins are:
- PlotModel.AxisChanged
- PlotModel.Rendered (this is an event we introduced for the initial rendering only, afterwards we unsubscribe from that event again. This event is getting fired by overriding RenderOverride in the PlotModel
- ArrangeOverride of our control is getting called

```
private void OxyPlotModel_AxisChanged(object sender, AxisChangedEventArgs e)
{
	var plotModel = (HHOxyPlotModel)sender;

	ResetSizes();
	foreach (var graph in _graphs)
	{
		GetAxesDimensions(graph.OxyPlotModel, plotModel);
	}

	UpdateGrid(plotModel);
}
```

```
private void GetAxesDimensions(HHOxyPlotModel model, IPlotModel changedModel)
{
	var graph = _graphs.FirstOrDefault(x => x.OxyPlotModel == model);
	if (graph == null)
	{
		return;
	}

	if (model.PlotView is not PlotView hhPlotView)
	{
		return;
	}

	// this is to ensure that the DesiredSizes are updated
	if (model == changedModel)
	{
		hhPlotView.UpdateLayout();
	}

	_plotMarginLeftColumn[((IHHFlowLayoutItem)graph).Column] = 20;
	_plotMarginRightColumn[((IHHFlowLayoutItem)graph).Column] = 20;

	// ref: https://github.com/oxyplot/oxyplot/pull/1562/files#diff-642b35762d6fe388d69fcaa009dfc05f2d2b45ceda65ba1894a5489ff8bb963b
	static double GetSize(Axis axis)
	{
		return axis.Position switch
		{
			AxisPosition.Left => axis.DesiredMargin.Left,
			AxisPosition.Right => axis.DesiredMargin.Right,
			AxisPosition.Top => axis.DesiredMargin.Top,
			AxisPosition.Bottom => axis.DesiredMargin.Bottom,
			_ => throw new InvalidOperationException(), // we don't do this for polar axes
		};
	}

	if (_plotMarginLeftColumn.Length > ((IHHFlowLayoutItem)graph).Column &&
		_plotMarginLeftColumn[((IHHFlowLayoutItem)graph).Column] < GetSize(model.YAxis))
	{
		_plotMarginLeftColumn[((IHHFlowLayoutItem)graph).Column] = GetSize(model.YAxis);
	}

	var newPlotMarginRight = 0.0;
	var rhsAxes = model.Axes.Where(x => x.Position == AxisPosition.Right);
	if (rhsAxes.Any())
	{
		newPlotMarginRight = rhsAxes.Max(GetSize);
	}
	else if (graph.ShowXAxis &&
			 model.PlotView is FrameworkElement plotView)
	{
		newPlotMarginRight = GetMostRightLabelWidth(plotView) / 2;
	}

	if (_plotMarginRightColumn.Length > ((IHHFlowLayoutItem)graph).Column &&
		_plotMarginRightColumn[((IHHFlowLayoutItem)graph).Column] < newPlotMarginRight)
	{
		_plotMarginRightColumn[((IHHFlowLayoutItem)graph).Column] = newPlotMarginRight;
	}
}
```

Which then eventually calls:
```
private void YAxisMargins(IPlotModel model)
{
	foreach (var graph in _graphs)
	{
		if (graph.OxyPlotModel.PlotAndAxisArea.Width == 0)
		{
			continue;
		}

		var margins = new OxyThickness(_plotMarginLeftColumn[((IHHFlowLayoutItem)graph).Column], 
									   double.NaN,
									   _plotMarginRightColumn[((IHHFlowLayoutItem)graph).Column], 
									   double.NaN);

		if (graph.OxyPlotModel.PlotMargins.Equals(margins))
		{
			continue;
		}

		graph.OxyPlotModel.PlotMargins = margins;
		if (graph.OxyPlotModel == model)
		{
			continue;
		}

		graph.OxyPlotModel.InvalidatePlot(false);
	}
}
```

The issue is that the GetSize function used to return always the correct value (before updating Oxyplot), and now sometimes it returns a value which is too small, resulting in a axis title, which is not fully visible:
![image](https://github.com/oxyplot/oxyplot/assets/88209166/1261ee48-bb6b-40dc-9d44-93984e4dcebe)


So it seems like the DesiredMargins are sometimes updated after we get the size and we don't update the plot margins in that case.
This is a transient issue, because it works often and only sometimes it doesn't. Also depending on if the control that is getting refreshed is currently visible on the UI or not. We have a tab control where each tab hosts our control. Then there is a button to refresh the plots, which would refresh all controls in all tabs, so only some are visible and some are not. So far we seem to have issues only with controls which are not visible. However with the old oxyplot version this wasn't the case and it always worked.
Don't get me wrong I'm not complaining about the new version. I know that we are trying to achieve something that OxyPlot wasn't particularly designed for and it's very difficult to provide a working example that shows that issue, that's why I was wondering if there is an example somewhere.

**Comment by VisualMelon** [comment]
Looking briefly, `DesiredMargins` will only be updated when the plot renders, and it may well be that the new provision is avoiding rendering when the plot is invisible, leading to a failure to measure (this is a pretty fundamental issue with OxyPlot that we've been trying to work out how to change for a while, as it would be useful to perform a layout pass without having to actually render anywhere for all sorts of reasons). For reasons that are not clear to me, the `Axis.Measure` method is public, so it may be worth calling that on the axes before querying the `DesiredSize` but that's just a guess and I can't be sure it won't have unpleasant side effects.

I'll try to take a closer look another time, as I've not quite understood what is happening here.

Another option for this sort of thing is to put all the axes on one plot and handle the visibility manually (and nothing else). You can set the `StartPosition` and `EndPosition` (values between 0 and 1) to determine how much of the RHS of the plot each axis assumes. With 2.1 you have additional axis margins which help with this, as in the not-very-well-named example: https://github.com/oxyplot/oxyplot/blob/85dd07dd719468e7cb00e7ccaaaf83d89e8bf0ad/Source/Examples/ExampleLibrary/Axes/AxisExamples.cs#L1594

**Comment by David-HH-Dev** [comment]
@VisualMelon thank you very much for the quick feedback.
My idea after reviewing the OxyPlot code, was to write our own LinearAxis implementation that derives from the OxyPlot one and override the Axis.Measure method and raise an event at the end, and then take this event as input rather than Axis.AxicChanged. Like this it should at least getting updated once the tab which wasn't visible before is getting activated or?
Looking at the example you posted, we will probably also do a case study if we can change from multiple plots with just one y-axis to just one plot with several axes stacked. We didn't really consider that before.

**Comment by VisualMelon** [comment]
Hooking measure sounds like a good idea; obviously will need to keep track of the state of all axes to find the minimum when any axis becomes narrower.
