### ISSUE TITLE
Domain expiring

### ISSUE THREAD

**Issue by objorke** [oxyplot/oxyplot#1300]
The domain name is expiring 2019-07-04. Renew it or not?

**Comment by objorke** [comment]
I suggest to move the content to https://github.com/oxyplot/oxyplot/wiki and delete the github pages.

**Comment by objorke** [comment]
Or keep the github pages on https://oxyplot.github.io

**Comment by agarcialeon** [comment]
@objorke I would vote for moving docs to github pages with the main repository website so both can follow the same theme and use markdown (that maybe will be more straightforward to use for contributors). 

Also I have created an [issue ](https://github.com/oxyplot/oxyplot/issues/1311)to implement Oxyplot for Blazor (via WebAssebly) so documentation can include interactive examples that can be tested inside the browser and replace the current fiddle.

**Comment by agarcialeon** [comment]
Also if Github pages allows to implement Try.NET the integration should be seamingless.

**Comment by objorke** [comment]
The domain has expired. 
Home page is now at: https://oxyplot.github.io
Documentation is at: https://oxyplot.readthedocs.io/en/latest/
Discussion forum is at https://oxyplot.userecho.com/

**Comment by mennodeij** [comment]
Hi, I just noticed that there are dead links on the homepage to docs.oxyplot.org

**Comment by agarcialeon** [comment]
@mennodeij @objorke I've updated the readme with the new domain url. Check pull request [here](https://github.com/oxyplot/oxyplot.github.io/pull/3). 

NOTE: Contribute page is still missing because I can't found an specific page for contribution in the new domain. 

If it exists, please change it or tell me to update it. If not, then we should consider to create one with the documentation toolkit or add in github a contribute.md as other repositories to provide guidance to new contributors.
