### ISSUE TITLE
Create stable release v2.0

### ISSUE THREAD

**Issue by objorke** [oxyplot/oxyplot#1332]
I suggest to change from "fixed scope" https://github.com/oxyplot/oxyplot/milestone/2 to scheduled releases.

**Comment by VisualMelon** [comment]
How can contributors help to expedite this? Should/could we compile a list of 'essential' changes so that contributors can focus their efforts, and sort out a release soon?

For example, I know it would help me greatly to have `HistogramSeries` on NuGet, but if we want to add `Color` to `HistogramItem` (#1305) that's something that should be dealt with first.

**Comment by objorke** [comment]
Added #1347 regarding the HistogramItem

**Comment by objorke** [comment]
I can review the milestone/2 so we can get there faster!

**Comment by objorke** [comment]
The milestone has been reviewed. And we have closed all issues!

**Comment by SkinnySackboy** [comment]
Will this version support netstandard2.0 or netcoreapp3.0?

**Comment by SkinnySackboy** [comment]
@VisualMelon ace thanks - by the current development branch do you mean develop, as opposed to the v2.0 branch, or will the v2.0 branch also include these changes?

**Comment by SkinnySackboy** [comment]
@VisualMelon many thanks, much appreciated.

**Comment by objorke** [comment]
https://github.com/oxyplot/oxyplot/releases/tag/v2.0.0
