### ISSUE TITLE
Does OxyPlot library supports .Net Core 2.2 version

### ISSUE THREAD

**Issue by Dhirajsakariya** [oxyplot/oxyplot#1335]
I am planning to use OxyPlot library for .Net Core 2.2 WPF app with Avalonia ReactiveUI.

I am getting below error. 
The value  for 'Child' property is null

When I add Oxy:Plot xaml in MainWindow.Xaml then getting this error
Platform: Windows 10
.NET version: .Net Core  2.2

Does OxyPlot library support .Net Core 2.2 ? 
If yes, do you have any example to share

**Comment by VisualMelon** [comment]
The 'core' OxyPlot library (OxyPlot.dll) targets .NET Standard. The WPF provision for OxyPlot does not, primarily because WPF does not yet support .NET Core, and never will support .NET Core 2.2. .NET Core 3.0 however _will_ provide WPF (on Windows only), and you can see some recent discussion about porting OxyPlot.WPF to .NET Core 3.0 in issue #1331.

**Comment by VisualMelon** [comment]
If you want to use Avalonia and no WPF, then this is possible with .NET Core 2.2; however, it is a bit fiddly. I can try to dig out an example I had somewhere if that would be useful.

**Comment by objorke** [comment]
OxyPlot.Wpf will support .NET Core 3.0, this is covered by #1331 
The core OxyPlot library is .NET Standard 1.0.
For Avalonia we have https://github.com/oxyplot/oxyplot-avalonia
