### ISSUE TITLE
HistogramHelper Collect API Revision

### ISSUE THREAD

**Issue by VisualMelon** [oxyplot/oxyplot#1345]
The API for the `Collect` methods in `HistogramSeriesHelper` could be better.

Currently the methods use an exclusive upper-bound for bins and essentially ignores elements that are not binned (it is optional whether they are counted for the purpose of computing frequencies).

Having now spent some time using the API (rather than rolling my own every time I needed as histogram as I would in the past), I have at no point benefited from either of these behaviours. Rather, when (for example) I have wanted to bin elements in the range `[0-1]`, I have been unable to do so, and was not informed that elements that were exactly 1 were not being counted. It is my opinion that the design I went with when implementing these methods was poor, and should be revised.

I would suggest the following (breaking) changes:

 - An `enum` should be introduced to determine the binning behaviour. The default value should throw when an un-binable item is observed, and options should also be provided to Count (i.e. `countUnplaced = true`) and to Ignore (i.e. `countUnplaced = false`).
 - Another `enum` should be provided to control whether the upper-most bin is inclusive or exclusive.

These parameters should be non-optional.

It should be noted that these a convenience functions, and will not be able to satisfy everyone's requirements; however, these changes would make it harder to misuse the API. The API is pretty new, and has not been released as stable. Changing the API in this manner would be a code-breaking change, so there is no risk of mysterious behaviour changes, and 'updating' calling code would be trivial.

I would be interested to hear any feedback.

I am more than happy to make the appropriate changes through the code-base (`OxyPlot` and `Examples`).

**Comment by Jonarw** [comment]
In my application I'm facing the problem that I have to present the user a histogram with previously unknown data range and often extreme outliers. These extreme outliers make algorithms with pre-defined bin breaks very inefficient. That's why I use a `Dictionary`-based approach to binning, something like this: https://gist.github.com/Jonarw/f21cac20061ec784c018de6cf13c2787

Of course this is no general purpose solution, as it only works with constant bin sizes. Therefore I'm not proposing this as a replacement for the existing algorithm, but more as an alternative approach to this topic, which may or may not make sense to include in the library (in addition to the existing algorithm).

Not having used the existing algorithm too much (for the above reason) I can't really comment on your proposed changes other than it sounds reasonable.

**Comment by objorke** [comment]
Could the upper-most bin always be inclusive on the high end? If not, an `enum` or `bool` argument sounds good.

I think the utility class should only cover the most common scenario. Otherwise there will be a lot of arguments/complex API (I think there are lot of possible binning strategies). If you need a custom binning strategy, you should write the logic in application code, in my opinion.

Counting the number of items below or above the range could also be a task for such custom code.

I don't see any unit tests for HistogramHelpers. We need this!
And I think the class should be moved from `Series\` to `Utilities/`

**Comment by VisualMelon** [comment]
I don't think the upper-bin should be inclusive by default; I think it would be better to always qualify this. Otherwise I agree with all your suggestions. I'll try to expedite this in the next few days.

**Comment by VisualMelon** [comment]
First pass is my [HistogramHelpers](https://github.com/VisualMelon/oxyplot/tree/HistogramHelpers) branch. Remove the `start/end` overload, instead providing a method to generate uniform breaks that can be passed to the other collect method (much easier to test). Feedback of course welcome.

Easiest way to see what has changes is to compare calls to the new and old API:

    # old
    var items = HistogramHelpers.Collect(samples, min, max, binCount, true);
    
    # new
    var binningOptions = new BinningOptions(BinningOutlierMode.CountOutliers, IntervalType.InclusiveLowerBound, includeExtremeValues: false);
    var binBreaks = HistogramHelpers.CreateUniformBins(min, max, binCount);
    var items = HistogramHelpers.Collect(samples, binBreaks, binningOptions);

Still to address:
 - Validation in `Collection` (e.g. reject `NaN` and infinite samples and breaks (though in theory infinites could be collected, they would not produce a valid `HistogramItem` so should reject)
   - Tests for this
 - Revise naming and documentation
 - Would it make sense to include interval information in `HistogramItem`? (e.g. whether the left and right bounds are inclusive/exclusive)
 - Would like to make `includeExtremeValues` an `enum` so that it is less ambiguous
 - More tests are probably in order
 - Work out how to make StyleCop work in VS 2017 so I can actually run it...

**Comment by VisualMelon** [comment]
I've actually committed the tests this time. I can't get StyleCop working, so I used the extension (#864) and address the numerous complaints it had.

The main open question in my mind is how to handle the situation where there are no samples assigned to any bins: currently it produces `HistogramItems` with `Area=NaN`. This isn't total nonsense, doesn't mess up the rest of the plot, is easy to detect, represents an edge case, and allows the API to be used 'safely' without significant pre-processing of the data, so I'd be inclined to keep this behaviour rather than throw.

**Comment by VisualMelon** [comment]
Latest commit to [HistogramHelpers](https://github.com/VisualMelon/oxyplot/tree/HistogramHelpers) includes the addition of the `Count` property as suggested over at #1347 as it is part of the API that needs testing for the `Collect` method. It also includes some style fixes which hopefully are welcome.

<hr />

I think the failure mode for `NaN` is fine at the moment, since it isn't clear to me that the behaviour is wrong, and throwing an exception in the condition where it would occur may break an otherwise perfectly serviceable plot.

<hr />

> Would it make sense to include interval information in HistogramItem? (e.g. whether the left and right bounds are inclusive/exclusive)

This would make sense if only for use by the `Contains` method, which currently assumes everything has an inclusive bound, and can therefore misreport where an item would be binned. In my opinion this represents a deficiency in the API, but I don't think it needs to be resolved presently. I'm open to suggestions as to how to resolve this without making the API too bitty (and I'm happy to implement suggestions for review/testing).

<hr />

At this point, I'm happy enough with the API and existing tests, so I'll put a PR together soon. I'm more than happy to implement additional tests if people suggest them.

**Comment by Jonarw** [comment]
Some feedback from my side, keep in mind that some of this may be opinion-based.

Regarding the case where there are no samples assigned to any bins: I think I would prefer to have all bins with `Area=0` - this seems more consistent with the non-edge-cases to me.

Some other stuff I noticed when glancing over the code:

`HistogramHelpers.cs`:
- Line 75: Return type could be `IReadOnlyList<HistogramItem>` or even `IList<HistogramItem>` to make it explicit that we return an in-memory collection
- Line 93: I would prefer `ToList()` instead of `ToArray()` - most of the time this saves you one allocation [[1](https://stackoverflow.com/questions/1105990/is-it-better-to-call-tolist-or-toarray-in-linq-queries)]. Plus you can use the more convenient `List<T>.BinarySearch(...)`
- Line 106: Could use an `Array` instead of `List` here to save the manual initialization

**Comment by VisualMelon** [comment]
I've effected those last 3 suggestions (commited and pushed). I'll take some time to think about `Area=0` and maybe write up a more full discussion, though I can't think of any negatives off hand.

**Comment by VisualMelon** [comment]
I went ahead and implemented `Area=0` for `count == 0` as suggested, with basic complementary tests. Does anyone have any other concerns? I'll promote this to a PR in the next couple of days if I have enough time to review it properly myself beforehand.

I have used NUnit's `Assume` in a couple of the tests, but it seems the VS 2019 tooling doesn't cope with this too well (acts as though the test wasn't run if an assumption isn't met). If this is a problem then I'll replace these with assert and commentary.
