### ISSUE TITLE
MagnitudeAxisFullPlotArea renders circles incorrectly

### ISSUE THREAD

**Issue by objorke** [oxyplot/oxyplot#1364]
Open the "Semi-circle polar plot filling the plot area" example.
Move the center to lower-left corner.
The magnitude circles are rendered incorrectly: 

![image](https://user-images.githubusercontent.com/439716/66688119-98ceb580-ec85-11e9-9fb7-7099137b8759.png)

**Comment by VisualMelon** [comment]
Similar issue in `Spiral full-plot area` example, where moving the center to the bottom of the plot causes a second set of grid-lines to be drawn which go out of bounds.

**Comment by VisualMelon** [comment]
It appears to be caused by `cornerangle_bottomleft` going outside the range 180-270. None of the other quadrants seem to go wrong. The picture case is when it ends up as 360 because the `atan2` is fed `0,0`. A similar effect can occur with `cornerangle_topleft`. A suitable fix is not immediately obvious to me, but the issue can be mitigated somewhat by filtering such unexpected values.
