### ISSUE TITLE
TimeSpan has overflowed because the duration is too long.

### ISSUE THREAD

**Issue by aliridha1510** [oxyplot/oxyplot#1595]
### Steps to reproduce

1. Scroll down a maximum level of Y-axes
 2.Oxyplot exception : TimeSpan has overflowed because the time is too long.

Platform: 
Windows 10 
OxyPlot.Wpf 2.0.0
.NET version: 3.1!

![image](https://user-images.githubusercontent.com/23260197/83773954-74e13980-a685-11ea-91b5-7c8bd351530a.png)
### Expected behaviour

![image](https://user-images.githubusercontent.com/23260197/83773568-f84e5b00-a684-11ea-9642-8bd12b7971ce.png)

### Code Example 
```
        public void SunriseandsunsetinOslo()
        {
            Model.Subtitle = "UTC time";
            Model.Title = "Sunrise and sunset in Oslo";
            var dateTimeAxis1 = new DateTimeAxis();
            dateTimeAxis1.IntervalType = DateTimeIntervalType.Months;
            dateTimeAxis1.MajorGridlineStyle = LineStyle.Solid;
            dateTimeAxis1.StringFormat = "MMM";
            Model.Axes.Add(dateTimeAxis1);
            var timeSpanAxis1 = new TimeSpanAxis();
            timeSpanAxis1.MajorGridlineStyle = LineStyle.Solid;
            timeSpanAxis1.StringFormat = "h:mm";
            Model.Axes.Add(timeSpanAxis1);
            var areaSeries1 = new AreaSeries();
            areaSeries1.DataFieldX2 = "Day";
            areaSeries1.DataFieldY2 = "Sunset";
            areaSeries1.Fill = OxyColor.FromArgb(128, 255, 255, 0);
            areaSeries1.Color = OxyColors.Black;
            areaSeries1.DataFieldX = "Day";
            areaSeries1.DataFieldY = "Sunrise";
            Model.Series.Add(areaSeries1);
        }
```

**Comment by VisualMelon** [comment]
This can be reproduced with any of the existing `TimeSpanAxis` examples.

I'm not sure how best to deal with this. This could be mitigated by adding

            this.AbsoluteMaximum = System.TimeSpan.MaxValue.TotalSeconds;
            this.AbsoluteMinimum = System.TimeSpan.MinValue.TotalSeconds;

To the `TimeSpanAxis` constructor so that (by default) it can't exceed the bounds it can handle.

**Comment by VisualMelon** [comment]
Which exception do you get and under which scenarios with that change?

In theory it should be seconds, because we're using `FromSeconds`, and for me it behaves as expected (i.e. clamps the axis so it can't escape the bounds) with a recent build (I'll try v2.0.0 as soon as I can find the right commit...).

**Comment by VisualMelon** [comment]
Looks like the behaviour is changed with Jonarw's 26f0c3bd698b92c2490d1f6a76a04ad4272b6b24, because it filters tick outside the logical range before outside of the rendering (i.e. before that commit, ticks were being created outside the `Minimum` and `Maximum`, being left to the renderer to filter them before drawing).

This sort of issue (axes escaping the bounds in which they can properly function) probably holds in a few other places: would setting default `AbsoluteMinimum` and `AbsoluteMaximum` values (with appropriate documentation) seem reasonable to everyone?
