### ISSUE TITLE
Display Count in Histogram Y axis ?

### ISSUE THREAD

**Issue by swethakini-ofc** [oxyplot/oxyplot#1644]
I am using HistogramSeries from Oxyplot 2.0. 

My values used are
List<double> sampleData= new List<double>() { 0,1,2,3,10,11, 25,  54, 66, 77, 88, 99, 100 };
double binWidth = 10;
int binCount = (int)Math.Ceiling(100 / binWidth);

I get below plot with height plotted on Y axis. 
Is there a way to display **count** on Y axis instead of height factor

![image](https://user-images.githubusercontent.com/60653002/90244921-5189f600-de4f-11ea-8710-aca044884bc7.png)

**Comment by VisualMelon** [comment]
There is no support for this, because the areas of the plots cease to be meaningful if they don't represent the area of the histogram items. If you have fixed sized histogram items, you can of course fudge this by making the area equal to the count times the width, e.g.:

    items = items.Select(hi => new HistogramItem(hi.RangeStart, hi.RangeEnd, hi.Count * hi.Width, hi.Count))

If you want counts, you might consider using a column series with a suitable category axis.

All that said, histograms with absolute counts do seem to be all over the place, and so long as the bins are fixed width it is probably OK: perhaps we should consider such a feature (i.e. add an enum to control whether the histogram plots area or count, with inline documentation explaining that the former makes no sense if you have non-uniform bins), and maybe change `Count` to a more generic `Volume` or `Quantity` with type `double` rather than `int`).

**Comment by VisualMelon** [comment]
Closing: if someone can present a serious use-case for this, then we can re-open it, but for the moment I don't think it makes enough sense, and it is easy enough to work around.
