### ISSUE TITLE
Variables in the legend

### ISSUE THREAD

**Issue by SynapseIkaros** [oxyplot/oxyplot#1657]
private Dictionary<Series.Series, OxyRect> SeriesPosMap { get; set; }
I can't use him.
So I modified him.
I can use it.

**Comment by Jonarw** [comment]
I'm sorry, I do not quite understand.
Is there a question in there?

**Comment by SynapseIkaros** [comment]
> 对不起，我不太了解。
> 那里有问题吗？

I need to do a MouseHover, to get the title of the legend

**Comment by SynapseIkaros** [comment]
This variable is private，So I modified him.

**Comment by Jonarw** [comment]
Is there an actual issue with the oxyplot library?
If not I think we can close this.

**Comment by VisualMelon** [comment]
@Jonarw I think the point is that it's impossible to locate where the entries in the legend are rendered from outside the legend, which could certainly be useful. For the time being, however, I would shy away from opening Legends up, because I anticipate we will want to make some changes to improve the hit-testing (which would facilitate the use-case described here and help with #1628 and #1631).
