### ISSUE TITLE
Series titles in legend not displayed in Chinese.

### ISSUE THREAD

**Issue by SynapseIkaros** [oxyplot/oxyplot#1659]

**Comment by SynapseIkaros** [comment]
I don't know why, but RectangleF can't print the title of the legend in Chinese.

//erro in Here ↓
var layoutRectangle = new RectangleF(0, 0, size.Width, size.Height);
//erro in Here ↑


                if (Math.Abs(rotate) > double.Epsilon)
                {
                    this.g.RotateTransform((float)rotate);

                    layoutRectangle.Height += (float)(fontSize / 18.0);
                }

                this.g.TranslateTransform(dx, dy);
                if (text == "测试1")
                {
                    // new Font("宋体", 20, FontStyle.Regular)
                    //new PointF(0.0F, 0.0F)
                    this.g.DrawString("测试1", font, new SolidBrush(Color.Red), layoutRectangle, this.stringFormat);
                }

                this.g.DrawString(text, font, this.GetCachedBrush(fill), layoutRectangle, this.stringFormat);

**Comment by SynapseIkaros** [comment]
![image](https://user-images.githubusercontent.com/53081122/93573176-636c3500-f9c9-11ea-8163-359b1119bbb4.png)

**Comment by SynapseIkaros** [comment]
这不是我想要的百分比,我不需要乘以100的百分比
That's not the percentage I want. I don't need to multiply it by 100 percent.

**Comment by VisualMelon** [comment]
Please open separate issues for each problem: it makes them easier to track, especially when the maintainers don't have a lot of time to keep track of things. Also, please always specify the version and platform: graphics issues are generally platform specific, and this information is necessary for us to reproduce things.

1. The issue with RectangleF sounds like #1385 (try Ceiling the width and height).

     Is that your code or ours? `layoutRectangle.Height += (float)(fontSize / 18.0);` won't work for all fonts, the text should be measured explicitly with the provided methods.

    Can you provide a minimal reproducible example for the issue with Oxyplot itself? I'm able to render Chinese text in the legend just fine in 2.0.

2. The issue with the percent is because format "P" formats translates a decimal into a percentage (it doesn't just put a "%" on the end), e.g. `0.5.ToString("P1")` -> `"50.0%"`. You could use a custom `LabelFormatter` instead: `xaxis.LabelFormatter = x => (x / 100).ToString("P1");`

**Comment by SynapseIkaros** [comment]
I used versions from git, not nuget versions.
It's c# winfrom
This is your code .
layoutRectangle.Height += (float)(fontSize / 18.0); 

Examples
            var lineSeries1 = new LineSeries()
            {
                Title = "曲线1",
                LabelFormatString = "",
                MarkerType = MarkerType.Circle,
                InterpolationAlgorithm = InterpolationAlgorithms.CanonicalSpline
            };
            var r = new Random(13);
            var y = r.Next(10, 30);
            for (int x = 0; x <= 100; x += 10)
            {
                lineSeries1.Points.Add(new DataPoint(x, y));
                y += r.Next(-5, 10);
            }
            plotModel1.Series.Add(lineSeries1);

**Comment by SynapseIkaros** [comment]
@VisualMelon

**Comment by VisualMelon** [comment]
@SynapseIkaros 

> layoutRectangle.Height += (float)(fontSize / 18.0);

Thanks, I've found it now. That piece of code does look odd... I'll have to look into it, but it won't be specific to legends (indeed, I don't think you can rotate legends, so it shouldn't apply at all).

With the example, I'm assuming it has the code necessary to add a legend;

    var legend = new Legend();
    legend.LegendTitle = "Legend";
    plotModel1.Legends.Add(legend);

I can reproduce the problem of the _series_ title not being displayed in 2.0 and pre-release. The legend title prints fine, so I guess this is what you meant (I'll update the title of the issue to avoid confusion). I'll look into this as well, but I'm pretty busy at the moment, so I might take a bit of time to work out a proper solution. It feels a lot like #1385, because if you provide multiple lines of text, then only the last line isn't rendered.

**Comment by SynapseIkaros** [comment]
> @SynapseIkaros
> 
> > layoutRectangle.Height + =（float）（fontSize / 18.0）;
> 
> 谢谢，我现在找到了。那段代码看起来确实很奇怪……我将不得不研究它，但是它并不是特定于图例的（实际上，我认为您不能旋转图例，因此它根本不适用） 。
> 
> 在这个例子中，我假设它具有添加图例所需的代码。
> 
> ```
> var legend = new Legend();
> legend.LegendTitle = "Legend";
> plotModel1.Legends.Add(legend);
> ```
> 
> 我可以重现在2.0和预发行版本中未显示_系列_标题的问题。图例标题可以很好地打印，所以我想这就是您的意思（我将更新问题的标题，以避免造成混淆）。我也会对此进行研究，但目前我很忙，因此我可能需要一些时间来制定适当的解决方案。感觉很像[＃1385](https://github.com/oxyplot/oxyplot/issues/1385)，因为如果您提供多行文本，则仅不显示最后一行。
I am in the code.
Var layoutRectangle = new RectangleF (0pje 0pr size.Widthje size.Height).
Width+10,Height+4.
In this way, you can print out Chinese normally.

**Comment by VisualMelon** [comment]
Yeah, it makes sense that adding more height makes the text appear, but that isn't a robust solution. I need to dig into WinForms again and see what it's doing.
