### ISSUE TITLE
WPF Oxyplot Updating

### ISSUE THREAD

**Issue by sushi19921992** [oxyplot/oxyplot#1683]
Hey guys,

So whilst we wait for 2.1 to become an official release (as @VisualMelon probably knows, we can't use it sadly until it's stable), we have always had a bit of an issue where we have a non-ui thread that is having to do a Dispatcher.Invoke call to the UI to update the graphs (and updating the graphs obviously is when you set invalidate data to true). So... the problem is is that this occurs up to 400 times and a good few times under half a second. After the 100th or so time, because the graph is being updated in real-time, the UI starts to slow down... heavily....

Is there a way to "lazily" update the plotting of the graphs? Don't know if anyone has any suggestions at the moment.

**Comment by Jonarw** [comment]
I guess you could consider updating the plot less often - there is no point in updating your plot 400 times in half a second when your monitor shows 60 fps in best case anyway.
The best approach to do this depends on your application; you could consider throttling the update calls (key word: 'debounce').

**Comment by VisualMelon** [comment]
Which platform are you using? On most platforms the plot will only be rendered when the operating systems asks the application to update (invalidating the plot just registers the control as dirty, it shouldn't do any real work). Are you sure it is slow because of the real-time updates, or could it just be the volume of data accumulating? (i.e. if the updates are stopped at some point, is panning/zooming still sluggish).

**Comment by sushi19921992** [comment]
> I guess you could consider updating the plot less often - there is no point in updating your plot 400 times in half a second when your monitor shows 60 fps in best case anyway.
> The best approach to do this depends on your application; you could consider throttling the update calls (key word: 'debounce').

I probably didn’t explain it properly. In total there will be about 400 calls to invalidate plot. This is because 400 series will be plotted (we have only shown a quarter of that due to performance issues with the plotting).

Not sure how throttling could work tho...

**Comment by sushi19921992** [comment]
> Which platform are you using (I assume WPF from the use of `Dispatcher`)? On most platforms the plot will only be rendered when the operating systems asks the application to update (invalidating the plot just registers the control as dirty, it shouldn't do any real work). Are you sure it is slow because of the real-time updates, or could it just be the volume of data accumulating? (i.e. if the updates are stopped at some point, is panning/zooming still sluggish).
> 
> Additionally, consider using the fire-and-forget variant of `Invoke` which won't block: that might be an issue in it's own right.
> 
> Edit: looks like WPF does call `PlotModel.Update` on `InvalidatePlot`.

Yep so... I have tried Invoke and InvokeAsync and there doesn’t seem to be a massive difference if any. I am using the dispatcher (I am reading from a device in a non UI thread and updating the graphs by calling dispatcher invoke and that calls the invalidation on every iteration i.e the 400 times it’ll call).

I have actually made it so the granularity of the points is also a quarter i.e each series would have about 2000 points but I’ve cut it to 500. Again tho.... this seems to become crippled after the first 100 series. Our plots are also in a tab control where there are multiple plots doing something similar.

It’s kind of a question of... how do we get around this? An idea was to push the invalidate plot calls to a queue of some sort from the non UI thread and have the UI touch the queue every now and then (lazy updating) but wasn’t sure how to implement this or if there is a way to play nice with Oxyplot with it.

**Comment by sushi19921992** [comment]
![oxyplot](https://user-images.githubusercontent.com/58184589/95359026-99fae880-08c1-11eb-91d6-1a52def6360f.PNG)

An idea to how bad it gets...

**Comment by VisualMelon** [comment]
> It’s kind of a question of... how do we get around this? An idea was to push the invalidate plot calls to a queue of some sort from the non UI thread and have the UI touch the queue every now and then (lazy updating) but wasn’t sure how to implement this or if there is a way to play nice with Oxyplot with it.

Yeah, sorry, I didn't realise OxyPlot.WPF called `PlotModel.Update` on invalidate rather than render (I'm much more familiar with OxyPlot.WinForms). The only solution I can think of to ensure the data is updated before rendering without performing unnecessary updates/code changes is to override `Update` on the plot model to do nothing except set a data-dirt flag, and then override `RenderOverride` to call `Update` based on the flag.

Re. the picture, you are using a Skia at the moment? We can't blame it on WPF's rendering performance then.

**Comment by sushi19921992** [comment]
Sorry that was the wrong picture. Switching between branches i.e. testing Skia which has a better performance (that was good performance lol) and the other branch which is not using Skia which is the one I was initially talking about.

**Comment by sushi19921992** [comment]
To be honest VS has been trying to "stop diagnostic session" for about 10 years and nothing so... let's just assumke this is WPF's rendering performance (which I have known to be notoriously bad....). Do you think applying those changes to the `Update` function and `RenderOverride` will actually help?

**Comment by sushi19921992** [comment]
![oxyplot1](https://user-images.githubusercontent.com/58184589/95361487-b51b2780-08c4-11eb-8519-2bbbe17d78be.PNG)

Managed to get a screenshot

**Comment by sushi19921992** [comment]
Using Oxyplot + Oxyplot.WPF Stable 1.0.0

**Comment by VisualMelon** [comment]
@sushi19921992 If it is spending its time in `Layout`, then no. I'm guilty of forgetting just how different WPF an WinForms are again: I think WPF is trying to render at a much higher frequency, and I guess you are just saturating the message pump.

It looks like the WPF renderer is designed such that you don't need to call `InvalidatePlot` on the UI thread (it calls into it itself, but not for update (it uses the sync lock)), so that's something to try. I'm just trying to make an example to mess with myself, because my intuition is not working. What @Jonarw originally suggested still sounds like a good idea: something as simple as setting up a timer to invalidate the plot at regularly intervals instead of on demand would be worth trying.

**Comment by VisualMelon** [comment]
1.0.0?! Crickey: is there are reason you aren't using 2.0.0?

**Comment by sushi19921992** [comment]
Hah I saw that crikey :P. Tbh I didn't even notice our version is still 1.0.0. We started using Oxyplot a year ago so maybe it was 1.0.0. then. Just updated it to 2.0.0. No performance difference sadly though...

So, 2 things, I could go with trying the timer option and figure out how I can do that nicely, but what were you saying about `InvalidatePlot` not needing to be called on the UI thread? Are we saying it can be called on the "non-UI" thread? How would the plots themselves visually be updated if they are not?

**Comment by VisualMelon** [comment]
@sushi19921992 the implementation of `InvalidatePlot` makes the dispatcher call itself: by not doing so, it leaves the call to `Update` on the calling thread. Thinking about it again, I think changing that will make things _worse_ however, because both update and render take an exclusive lock, and if you queue up lots of update calls on different threads, the UI thread may quickly become starved instead.

**Comment by sushi19921992** [comment]
Yeah I just tried and it looks pretty bad.... 

So perhaps @Jonarw 's suggest is the best? Potentially just have an timer that calls invalidateplot every X number of seconds. I do wonder though.... if even that will help... probably is, if we call InvalidatePlot and the everything gets updated, it will slow down horrendously... and I'm more thinking it's because there's too much going on maybe? I notice it is blitz speed when you "tab" away and the plot is not visible on the screen, but when it's visible again, that's when it becomes crippled. It's only one call per 0.2 seconds but a total of 400. So over X number of seconds, like ~30 seconds, we've finished but it slows down on each call...

**Comment by VisualMelon** [comment]
@sushi19921992 when you tab away, it won't be rendering, so that helps address that question.

> It's only one call per 0.2 seconds but a total of 400

Oh sorry, I thought you were making hundreds a second. I see what you meant in that second comment now.

It does sound just like the volume of stuff to render is large and it's taking a while. The cost of rendering is just a function of how much stuff there is (and what type of stuff: markers and text are fairly notorious): that is, it is not a function of how much stuff has changed.

The ideal way to debounce would be detect would be to drop render render calls that take place while rendering, and after rendering check whether anything was dropped (and then queue a re-render), because that ensures you never have anything waiting for anything else, but that will be fiddly, and nothing will solve the problem of rendering being too slow to keep up.

**Comment by sushi19921992** [comment]
Yeah... :\ man this is annoying. I tried a timer by creating a queue of actions, where those actions where just the "InvalidatePlot" calls. I made the timer that actioned all invalidate calls every 2 seconds. Only problem with THAT now is that it's quick for 2 seconds, then UI lags for a little bit then continues like normal.... hmph... ¬_¬

**Comment by sushi19921992** [comment]
Apart of me is thinking this is just not an issue with even queuing. When nothing is happening, no invalidate or anything, dragging the graph around causes some serious lag as well... this is with literally nothing happening. I thought Oxyplot could handle all these series but it is struggling even with most of them not being visible with only a small number of points...

**Comment by Jonarw** [comment]
I guess with that many points the only way to get rid of UI lag is to not render on the UI thread. Unfortunately that is not possible with WPF.

It is possible with SkiaSharp however, but not (yet) implemented in oxyplot. At work I use a modified version of the `OxyPlot.Skiasharp.Wpf` `PlotView` which renders in a background thread in combination with a debouncer, which works pretty well. However I can't share the code for this.

I am planning to re-implement this at some point into OxyPlot, but I don't want to promise any sort of timeline.

**Comment by sushi19921992** [comment]
That sounds pretty cool - I haven't got much experience with coding for rendering so it would probably take me a while to do what you're doing, plus SkiaSharp is not something we can use as there's not a stable version of it yet sadly. I feel like every point I turn to with this, we are gonna have a performance hit...

**Comment by sushi19921992** [comment]
It seems like waiting until the SkiaSharp stable version is released is the only way to potentially solve this :\

**Comment by VisualMelon** [comment]
@sushi19921992 mostly out of interest, which series are you using, do they have markers, and does your data have monotone X values? If so, they should be efficiently filtered; it not, off-screen points are still passed to the renderer, and usually there will be more of them (when everything is on-screen, they tend to be more tightly packed, and in e.g. line-series there is a minimum segment length below which they are culled). I wonder if maybe we could do more culling early on, because the performance is really shoddy in WPF at the moment when I'm sure it could be better.

**Comment by sushi19921992** [comment]
We use both scatter series and line series. The scatter series is fine, the line series is just as slow as a donkey.

The code we have is something like:

                // Set visibility to true for now...
                var series = new LineSeries
                {
                    Title = formattedDast,
                    Tag = ueId,
                    MarkerType = MarkerType.None,
                    TrackerFormatString = TrackerFormatStringForPlots,
                    IsVisible = true
                };

                //Create interpolated colour for the line series
                Color red = Color.FromRgb(255, 0, 0);
                Color blue = Color.FromRgb(0, 0, 255);
                Color interpolatedColor = interpolatedCol;

                series.Color = OxyColor.FromRgb(interpolatedColor.R, interpolatedColor.G, interpolatedColor.B);

**Comment by sushi19921992** [comment]
@VisualMelon On the plus side... how's the stable release of SkiaSharp.Wpf looking? Is there a rough estimate to when a stable release might be ready?

**Comment by VisualMelon** [comment]
There is nothing else I want to see in it, but I do want to sort out the getting-started documentation with the removal of WPF/XAML support. If I get around to doing that this weekend, I'd personally have no issue with releasing the first Preview the weekend thereafter.

**Comment by sushi19921992** [comment]
> There is nothing else I want to see in it, but I do want to sort out the getting-started documentation with the removal of WPF/XAML support. If I get around to doing that this weekend, I'd personally have no issue with releasing the first Preview the weekend thereafter.

Does that mean Oxyplot will not be supporting WPF/XAML in the future?

Sweet that sounds awesome :). And that’s going to be an official stable release as opposed to the unstable releases - just confirming.

**Comment by VisualMelon** [comment]
@sushi19921992 

> Does that mean Oxyplot will not be supporting WPF/XAML in the future?

Indeed. See the discussion in #1658

> Sweet that sounds awesome :). And that’s going to be an official stable release as opposed to the unstable releases - just confirming.

Yes, but see the release plan in #1671 for (the lack of) details of the timeframe

**Comment by sushi19921992** [comment]
> @sushi19921992
> 
> > Does that mean Oxyplot will not be supporting WPF/XAML in the future?
> 
> Indeed. See the discussion in #1658
> 
> > Sweet that sounds awesome :). And that’s going to be an official stable release as opposed to the unstable releases - just confirming.
> 
> Yes, but see the release plan in #1671 for (the lack of) details of the timeframe

Cool beans. Sounds good! I will definitely keep watching to see if it is released next weekend as we might be able to pick it up and use it officially!

Thanks :)

**Comment by sushi19921992** [comment]
@VisualMelon what do you reckon timescale would be on a proper official release and not a prerelease?

**Comment by VisualMelon** [comment]
@sushi19921992 it depends on how many bugs we find with the pre-release: If we have to deal with lots of problems, it might take a while.

**Comment by VisualMelon** [comment]
2.1 has now been released.
