### ISSUE TITLE
Why does the millisecond number of time axis be 4 digits？

### ISSUE THREAD

**Issue by SynapseIkaros** [oxyplot/oxyplot#1702]
c#  winfrom  

           var axisX_Time = new DateTimeAxis()
            {
                Key = "X0",
                Position = AxisPosition.Bottom,
                Minimum = DateTimeAxis.ToDouble(d),
                Maximum = DateTimeAxis.ToDouble(end),
                MajorGridlineStyle = LineStyle.Solid,
                MinorGridlineStyle = LineStyle.Solid,
                LabelFormatter = x => DateTimeAxis.ToDateTime(x).ToString("ss.ms"),
                MajorStep = 1.0 / 24 / 60 / 10,
                MinorStep = 1.0 / 24 / 60 / 4 / 15,
                IsZoomEnabled = true,
                MaximumPadding = 0,
                MinimumPadding = 0,
                TickStyle = OxyPlot.Axes.TickStyle.Outside
            };

**Comment by VisualMelon** [comment]
I'm afraid I don't understand the question, but I presume the problem is the format passed to [`DateTime.ToString(string)`](https://docs.microsoft.com/en-us/dotnet/api/system.datetime.tostring?view=netcore-3.1). As far as I'm aware, "ms" doesn't mean anything: you probably want "ff" (or "fff" or something) for fractional seconds.
