### ISSUE TITLE
.NET 5.0 support

### ISSUE THREAD

**Issue by LeoYang-Chuese** [oxyplot/oxyplot#1739]
### Support for .NET 5.0 

NET 5.0 has been released, are there any plans to support .NET 5 as a supported target platform?

**Comment by VisualMelon** [comment]
There is no plan as such, but I'm not aware of anything stopping us adding it to the list of target frameworks. This should certainly be done for the WPF and Winforms provisions, but I don't think there is any benefit to adding it where current we target net standard (e.g. the core library and ImageSharp)

I'm trying to finish a big project at the moment (read: a few months yet), which has rather dampened my capacity to work on my OxyPlot TODO list, but if someone else wants to put a PR together adding .NET 5 support to WPF, WinForms (should be pretty easy) I'll be happy to review it.

**Comment by G18SSY** [comment]
From what I can tell .NET 5 is already supported.

When building a .NET 5 targeted project the netcoreapp3.0  target in the OxyPlot.* NuGet packages is used (because effectively .NET 5 is just the next .NET Core iteration after 3.1). I did a quick test to confirm (using WPF) which builds and runs fine with no warnings. Test project is [here](https://github.com/G18SSY/OxyPlot-Net5Test) if you would like to test yourself.

**Comment by VisualMelon** [comment]
@G18SSY thanks for testing!

**Comment by LeoYang-Chuese** [comment]
NET 5.0 for a while, and so far no compatibility issues have been found, great!
