### ISSUE TITLE
Line Series with style for extrapolated/intropolated regions.

### ISSUE THREAD

**Issue by Doeharrrck** [oxyplot/oxyplot#1740]
I would suggest a new derived line series to indicate that parts of a curve have been extrapolated/intrapolated. This would be similar to the ThreeColorLine series but the visualization would depend on the horizontal coordinate and not the vertical one. 

I have added an [implementation](https://github.com/Doeharrrck/oxyplot/blob/develop/Source/OxyPlot/Series/ExtrapolationLineSeries.cs) and [examples](https://github.com/Doeharrrck/oxyplot/blob/develop/Source/Examples/ExampleLibrary/Series/ExtrapolationLineSeriesExamples.cs) to my fork of the project.

The examples look like this:
![LineFit](https://user-images.githubusercontent.com/46654057/107152416-f94c3080-6967-11eb-9203-58fe518f8a7b.PNG)
![Interpolation](https://user-images.githubusercontent.com/46654057/107152418-fd784e00-6967-11eb-8b01-ff002c65da67.PNG)

Compared to a normal LineSeries, the class ExtrapolationLineSeries has three additional properties:
- Intervals: Gets or sets an IEnumerable<Tuple<double, double>> in which the curve is displayed in extra/interpolated style. Can be set to null. If not null, the intervals must be ascending and may not overlap. Otherwise an InvalidOperationException is thrown. Positive and negative infinity are also legal delimiters. 

- ExtrapolationColor: Gets or sets the color of the intervals in which the curve is visualized as extra/interpolated. In addition the line style is assigned only to these intervals while the rest of the line is in solid style.

- IgnoreExtraplotationForScaling: If set to true, the extrapolated intervals are not taken into account when the minima and maxima of the dataset are calculated. Hence, the extrapolated line will also not scale the axes.

Is it possible to contribute my work?

**Comment by VisualMelon** [comment]
This looks interesting, though I think it'll be a few days before I get around to taking a proper look at this. I think the main question would be whether this is too niche a use-case to add it to the main library (means it has to be maintained forever).

**Comment by Doeharrrck** [comment]
Ok, let me know when you had time to take a look. Of course, I would also take responsibility for maintaining issues related to this class.

**Comment by VisualMelon** [comment]
Hurried notes from a quick glance:
 - Prefer not to have Tuple on public API
 - Using `ActualDashArray` in the 'unusal' part of the plot is odd; would prefer that was preserved in the non-extrapolated, and a separate `Extrapolated` property for the extrapolated case (more discoverable and consistent)
 - `IEnumerable` property is not ideal; can probably be replaced with `IReadonlyList` since it has to be enumerated fully
 - 'limiting' looks dodgy
   - Would be nice to relax need for ordered input
     - Could be done once in `UpdateData`
       - Would be nice to build an efficient representation once (i.e. binary searchable array) that can be re-used, e.g. for `UpdateMaxMin` (looks slow at the moment) and rendering (note: similar logic in grid-line rendering, though that has to deal with the overlapping case)
 - Does it make sense to render markers on such a plot? (not in the extrapolated region, right?)
   - Implementation doesn't render markers, but does show it in the legend
   - Actually, could this be an annotation rather than a series? (really must write up a proposal for showing annotations in the legend)
 - Will need a StyleCop pass
   - Header needs update
   - Lots of `this.`
 - Example inline doc is wrong

The implementation is nice and simple; not run the code yet. Can you provide any 'real world' examples of this sort of plot being used? (Do other libraries provide this feature?). (Want to check it has applicability, and that it doesn't behave in an unexpected way).

**Comment by VisualMelon** [comment]
@objorke @Jonarw would this be too niche to put in the main library? (I would say no, given we have Two- and ThreeColorLineSeries). My main concern is that it feels more like an annotation than a series.

The various API issues can be easily resolved as part of a PR, but the implementation seems fine (can do more aggressive testing as part of a potential PR).

**Comment by Doeharrrck** [comment]
Thank you for taking a look at this! 
- In fact I am also not too happy with having these tuples in the interface (or using generic tuples in general). In my original working project I have a similar `Interval` struct with Minimum and Maximum properties, derived Range property, and simple Methods like `Contains(double value)` or `IntersectWith(Interval other)`. I didn't want to add it here because I didn't know where to put such a general class which is only used for one specific purpose.
- The restriction on the intervals could be easily relaxed with such a struct. There is in fact no need why they must be in ascending order or ordered at all. The only real constraint is that they may not overlap with each other.
- Replacing the IEnumerable with a List is not a problem. However, I do not understand why this should be a IReadonlyList because the client wants to modify it. Or did you mean a list without a public setter like it is used for the Points collection?
- I have to take a look on the calculation of the DashArrays first but using them for the normal part of the line and having another property for the extrapolated part would make it even more flexible because two different styles could be used.
- Markers usually don't make sense. In the use case that I have usually in mind, there are data given by a scatter series or by another line series. The `ExtrapolationLineSeries` is then only be drawn as a fit line or regression line. So should I just remove drawing of the markers?
- The reason why I implemented this to be a series was in fact exactly that I wanted to have it in the legend (see my next post).
- I have already corrected the headers. I will do the other changes later this week.

**Comment by Doeharrrck** [comment]
One example plot is this (older) plot of [Moore's law with extrapolation](https://www.researchgate.net/figure/This-graph-of-Moores-law-shows-the-regularity-of-improvements-in-transistors-over-a_fig1_239580581). I will check whether I can find a source for the numbers so I could create another browser example from it with a logarithmic axis scale.

The original reason why I wrote this class was for my project in life science. A sample (e.g. a candidate for a medical drug) is injected over a sensor surface. The signal in the plot shows the amount of sample bound to this surface. 
![image](https://user-images.githubusercontent.com/46654057/107579285-30834180-6bf5-11eb-9f70-e0d2e34fb038.png)

Between 0s and 100s the sample is injected and the signal goes up because it is bound to the surface by association. After the injection has ended at t=100s, the remaining sample dissociates from the surface. Both regions are described by different differential equations with parameters which are found using a least square fit. The red line cursors are used to determine the data used for the association fit, the blue ones to constrain the data of the dissociation.

So the usage of the `ExtrapolationLineSeries` here is to show how the solution of the differential equation describes the original data also in those regions that were not used for the fit.

Over the years I have made various similar plots and I think it is quite common in life science or some parts of natural science in general. In earlier years, I used Measurement Studio by National Instruments which didn't support this feature. My workaround was usually to plot several lines over each other. First a dashed line over the entire range and then solid intervals on top.

**Comment by VisualMelon** [comment]
Thanks for background!

 - A general purpose `DataRange` type could reside in the `OxyPlot` namespace (along with `DataPoint`). I can't immediately thing what trouble it would cause, but I wouldn't object to a dedicated type for this specific purpose living along with the `Series` (e.g. like `RectangleItem` and `HistogramItem`).
 - Regarding `IReadonlyList`, I should have said `List`, which indeed would be getter-only (like `DataPointSeries.Points` and friends).
 - Regarding markers, the most important thing is consistency, and I think they probably should be supported if this remains a series. I can imagine that you might have 'real' data samples and 'guessed' samples (e.g. due to temporary communication drop-out), and this would provide a sensible solution of that; though, I can see they are not applicable in your use-case, and their inclusion might warrant separate styles (or at least color) for markers in the interpolated region. Regarding the legend, it would be nice if it showed the normal and extrapolated styles (e.g. half and half) to distinguish it from line series with broken regions.

Notes on whether this could be an annotation:
 - If I can drag myself away from #1640, I'll try to design an abstraction so that annotations can exist on legends and expedite that. I've seen requests for it a few times (linking #1697 before I lose track of it again) and it would make trendlines a much nicer experience.
 - Annotations don't contribute to min/max at-all the moment, but otherwise the series/annotation distinction is pretty arbitrary

**Comment by objorke** [comment]
I think this would be great to have in the main library! Implementation looks good, and I agree with VisualMelon's suggestions. If it gets too difficult to maintain, it could be moved to the Contrib library (#1400) at a later time.

To me, it sounds good to have this as a series, so it could easily show up as one item in the legends area. The intrapolation/extrapolation parts could be regarded as annotations, but I think it is a good idea to keep all together in a single series object.

The intervals only works for the x-axis, right? Is this limitation OK? Ans is this only useful for intrapolated/extrapolated data? Could it be used for other continuous datasets that have different "modes"? Could it be a more general "TwoStyleLineSeries" or "MultiStyleLineSeries"?

**Comment by VisualMelon** [comment]
>  The intrapolation/extrapolation parts could be regarded as annotations,

I was thinking more the whole series could be an annotation, since it fills the role of a trendline in the original example, but

**Comment by VisualMelon** [comment]
(sorry, wrong button)

**Comment by Doeharrrck** [comment]
Extending the scope to a more general MultiStyleLineSeries would of course also be an option. In fact, I wondered why there is a TwoColorLineSeries and a ThreeColorLineSeries instead of a MultiColorLineSeries or even MultiStyleSeries.
The current implementation only works for the x-axis and supports two different colors/styles (one for inside an interval and one for outside of any interval). 
The question is what an interface for a more general class could look like. I see two options:

1. Allow different styles either in horizontal OR vertical direction
  - There is one default color and style which can be set using the normal LineSeries' properties
  - The client can set horizontal or vertical mode using a `StyleMode` property
  - The client adds support objects (e.g. named `StyleInterval`) to override the default color and style 
  - These `StyleInterval` class would have these properties
    - Minimum
    - Maximum
    - Color
    - Style 
2. Define Rectangles in which the default color and style gets overriden. However, this might be to complicated for clients because also here the client would be responsible to take care that the intervals don't overlap.

**Comment by Doeharrrck** [comment]
Another remark: the `IgnoreExtraplotationForScaling` property that I have now would probably be removed in such a more general class because I cannot see how it would fit there.

**Comment by Doeharrrck** [comment]
Hi again, I have implemented most of the suggestions and also ran a check with StyleCop.Analyzers. Should I create a pull request for the ExtrapolationLineSeries already?

**Comment by VisualMelon** [comment]
@Doeharrrck if you're happy with it, feel free to open a PR. I'll try to take a proper look over the weekend.
