### ISSUE TITLE
DataPointSeries.Points and AreaSeries.Points2 are not exposed in OxyPlot.Wpf

### ISSUE THREAD

**Issue by shimimana** [oxyplot/oxyplot#1745]
Hi,
I found DataPointSeries.Points and AreaSeries.Points2 are not exposed in OxyPlot.Wpf.
I'd like to fill between 2 lines in WPF app, so I tried to update their wrapper classes.
Since I'm a newbie of this project, could you experts review my patch?
I'm not sure Points.Clear() should be called outside null check, or inside the if.

[diff.txt](https://github.com/oxyplot/oxyplot/files/5988650/diff.txt)

Hope this makes sense and helps someone.

**Comment by VisualMelon** [comment]
The WPF/XAML provision has moved to https://github.com/oxyplot/oxyplot-contrib

Feel free to open another issue over there, and a PR if you are happy for us to use your implementation and want a proper review. You may have to make some adjustments, because there have been some changes in the WPF/XAML stuff since it moved to contrib.

The current design expects the use of the `ItemSource` property, which is expected to expose the X/Y and X2/Y2 values. The problem with the clear/add process is that it will make visual-only updates expensive, because it also has to copy the data-points around. It may also violate some of the assumption behind the update calls, but I think that's unavoidable.

**Comment by shimimana** [comment]
Thank you for your information and suggestion.
I know ItemSource is the interface to access, and I can understand what you mean.
I'll check the latest source code and create a new patch if necessary, though I feel it is not.

So please close this ticket if you don't mind.
I'm glad to getting feedback from you.
