### ISSUE TITLE
CI for the Xamarin projects

### ISSUE THREAD

**Issue by objorke** [oxyplot/oxyplot#274]
The following projects should also be continuously integrated:
- OxyPlot.Xamarin.Android
- OxyPlot.Xamarin.iOS
- ~~OxyPlot.Xamarin.Mac (must be built on a Mac)~~
- OxyPlot.Xamarin.Forms (must be built on a Windows machine due to the Windows app renderer)

**Comment by objorke** [comment]
There is a thread on the appveyor forum:
http://help.appveyor.com/discussions/suggestions/167-need-support-for-xamarinandroid-and-xamarinios

See also
http://xamarin.com/faq#q33

**Comment by david-laundav** [comment]
There is further information in the following article:
http://developer.xamarin.com/guides/cross-platform/ci/

**Comment by tibel** [comment]
I think there will be problems with resolving the dependencies here.
Especially `OxyPlot.Mobile` and `OxyPlot.Xamarin.Forms` will have problems,
because `OxyPlot.WP8` and `OxyPlot.WindowsUniversal` are build by AppVeyor.

Best would be that the Xamarin build depends on `OxyPlot.Core`, `OxyPlot.WP8` and `OxyPlot.WindowsUniversal` nuget packages only.

@mattleibow Do you have any suggestions also how this relates to https://github.com/oxyplot/xamarin-component?

**Comment by tibel** [comment]
For me the versions of the published nuget packages seems to be a little random.

Package | Version
------- | -------
OxyPlot.Xamarin.iOS | 2015.1.721-alpha
OxyPlot.Xamarin.Mac | 2015.1.781-alpha
OxyPlot.Xamarin.Android | 2015.1.721-alpha
OxyPlot.Mobile | 2015.1.804-alpha
OxyPlot.Xamarin.Forms | 2015.1.804-alpha

Correct me if I'm wrong:
- the build currently uses the Xamarin.Mobile solution
- which rebuilds all the dependent (native) projects (e.g. OxyPlot.WP8)
- but OxyPlot.WP8 was build by AppVeyor already (duplicate?)
- the nuget packages for (e.g OxyPlot.Xamarin.iOS) are not updated

For me it looks like if it would be easier to maintain when:
- OxyPlot.Xamarin.Forms is build last
- does not rebuild the native projects
- only depend on the published nuget packages (no problems with different versions of the packages)
- so it would make sense to have it in a separate repo because of the above

@objorke What do you think on the Xamarin.Forms build?

**Comment by objorke** [comment]
I agree that this must be fixed!
I am not sure if the WP8 should be built at Appveyor or by Xamarin - I guess it is convenient to build everything related to Xamarin.Forms in one place.

@mattleibow what do you think?

**Comment by tibel** [comment]
@objorke Then Xamarin Forms will build nearly everything (e.g. OxyPlot.WindowsUniversal) in the future. I'm not so sure if this is a good idea.

For me Xamarin.Forms is an (incredible) abstraction layer on top of the native parts. Therefor I think it is different to the other packages (one nuget package per UI technology).

**Comment by objorke** [comment]
Should the Xamarin Forms projects reference the native OxyPlot NuGet packages?

**Comment by mattleibow** [comment]
@objorke I agree with @tibel. Xamarin.Forms is an abstraction and should be separate. And, as you mentioned, forms should reference the native packages.

**Comment by mattleibow** [comment]
@objorke building the packages - I think it would be easiest if CI could build as much as it can. Such as the WP8 and WinU. Then, only the Android, iOS, Mac, Forms needs to be built by "hand" as it were.

We are getting a CI together so that we can point it at a git repo and then let it do it's magic, but it is taking a bit of time due to priorities.

**Comment by objorke** [comment]
I am removing "OxyPlot.Mobile" from the issue description

**Comment by objorke** [comment]
It should now be possible to build the Xamarin projects on AppVeyor!
http://www.appveyor.com/docs/lang/xamarin

**Comment by objorke** [comment]
I understand AppVeyor cannot build the Mac project yet. #510

**Comment by mattleibow** [comment]
You can give it a go. I haven't used AppVeyor to build Xamarin projects yet. I would be very interested to see what happens. if it works, we can remove the supported platforms from the Xamarin CI

**Comment by tibel** [comment]
MonoMac and Xamarin.Mac is handled by a separate issue
