### ISSUE TITLE
Xamarin Forms OxyPlot init

### ISSUE THREAD

**Issue by objorke** [oxyplot/oxyplot#363]
Can we get rid of the `OxyPlot.Xamarin.Forms.Platform.*.Forms.Init()` code?
Could this be related to #358?

See the section about 'initialize renderers' on
http://oxyplot.org/documentation/hello-xamarin-forms

**Comment by mattleibow** [comment]
I don't think this can be avoided. Without it, the linker will remove the type as it is not directly referenced.
What can be done to make the API "neater" is to include the Init method on the actual renderer. This will help avoid the conflicting namespaces, but will break existing apps and they will have to be updated.

**Comment by objorke** [comment]
There should be a 'recommended practice' about how to do this in custom control libraries...
What are other Xamarin Forms components doing?

http://developer.xamarin.com/guides/cross-platform/xamarin-forms/custom-renderer/

**Comment by mattleibow** [comment]
I am asking our experts, but one of our guys uses the Init method:
https://github.com/jamesmontemagno/Xamarin.Plugins/tree/master/ImageCircle

**Comment by objorke** [comment]
I found that the renderer assemblies had to be loaded before calling Forms.Init() but I notice that ImageCircle seems to require the opposite.

**Comment by mattleibow** [comment]
Theoretically, the order shouldn't matter as nothing is actually done. It is just for the linker at compile-time. But let me try this again and make sure.

**Comment by objorke** [comment]
I was thinking if the bait-and-switch trick could be used such that `OxyPlot.Xamarin.Forms` assembly is not loaded but the `OxyPlot.Xamarin.Forms.Platform.X` (including the renderer) is loaded when the user creates a `OxyPlot.Xamarin.Forms.PlotView`. Or do I misunderstand the bait-and-switch? I know the renderers are different, but we don't need to access those from portable code.

**Comment by mattleibow** [comment]
The way the bait and switch works is to create an assembly named `Something.dll`. We code against this in a PCL. For the final app, we use another assembly, but with the SAME name. This way, the PCL gets a PCL dll, and the app gets the platform dll. This works as the app is looking for an assembly with a specific name, rather than a specific assembly. The bait and switch is just a fancy name for using different assemblies with the same name.

For the Forms case, I think the framework is designed for multiple assemblies. If we wanted to do the bait and switch, all the assemblies will need to have the same name and all will have to include the PCL code in all the assemblies. Usually for visual code, each platform has a separate assembly.

**Comment by tibel** [comment]
If I understand you right:
- bait-and-switch can/should be used for the OxyPlot.Xamarin.Forms assemblies
- all the OxyPlot.Xamarin.Forms* assemblies should have the same name

**Comment by tibel** [comment]
I close this as #632 should have fixed this
