### ISSUE TITLE
OxyMouseEvents not caught due to InvalidatePlot()

### ISSUE THREAD

**Issue by cfeltch537** [oxyplot/oxyplot#382]
I noticed that my MouseDown (attached to my Model or Series) event handlers appear to not fire when my plot is updating. Is there a workaround/solution for this? 

E.g) I have a PlotModel that I update fairly rapidly, ~30Hz. Certain MouseDown events (~ 1 out of 5) are not recieved by my handler(s), and it appears to be caused by the mouse events coinciding with occurrences of Model.InvalidatePlot(true/false).

**Comment by HermanEldering** [comment]
I have the same issue. It works fine when I don't call InvalidatePlot. In my case MouseDown is lost more often than MouseUp. It basically makes the OxyPlot graph unusable in this situation.

@cfeltch537 has posted a workaround on stackoverflow: http://stackoverflow.com/questions/29565113/oxyplots-mouse-events-are-not-caught-while-model-invalidated

I'd prefer not to use that work around as is because it makes updating the OxyPlot references more difficult. Perhaps it would be acceptable to include the grid inside PlotView within the OxyPlot library?

**Comment by silviubogan** [comment]
How can this issue be reproduced? How can it be verified that this issue is solved or not?

I am trying to solve #1081.

Thank you.

**Comment by HermanEldering** [comment]
@silviubogan I don't have example code that I can share. But there are two parts to this problem 1) you need to update and invalidate the plot frequently and 2) you need to use/check the MouseDown/MouseUp events.

I think the problem in this ticket is caused by the UI elements being destroyed and recreated. When an UI element is destroyed while it is handling events then those events may be lost, or the events might happen in the time after the old UI is destroyed but before the new UI has been created?

The change in my pull request adds an extra UI element (Grid) that is on top of all the other elements which grabs the events. Because this Grid is not destroyed it does not suffer the problem with losing events.

When the tooltips depend on the WPF hit-testing/events that will probably suffer from the same issue as this ticket, unless we can find a way to properly prevent events being lost when quickly destroying/recreating the UI.

I can test changes to OxyPlot in one of the applications I am responsible for that was impacted by this bug.

**Comment by silviubogan** [comment]
@HermanEldering Please, when you can, test in your application [this OxyPlot fork branch](https://github.com/silviubogan/oxyplot/tree/wpf-tooltips-not-displayed) (it is related to the same issue: #1081).

Thank you.
