### ISSUE TITLE
Oxyplot.GtkSharp: Port to gtk-sharp-3

### ISSUE THREAD

**Issue by juergenhoetzel** [oxyplot/oxyplot#525]
are there any plans to update to gtk-sharp-3 from gtk-sharp-2?

See: https://github.com/fslaborg/FSharp.Charting/issues/76

**Comment by sevoku** [comment]
I made a gtk3 port some months ago, but I didn't finish it because of the project structure complexity (I had simply rewritten the Gtk project). The major difference between Gtk2 and Gtk3 is drawing (no Expose event) and the sizing of widgets.

@objorke: what would be the best way to solve this?

1. It must be a separate project/solution file, would OxyPlot.GtkSharp3 be ok?
2. Should Oxyplot.GtkSharp be renamed (e.g. Oxyplot.GtkSharp2, breaking change!)
3. It would make sense to share code between both versions, since the differences are not very big. The easiest (dirty) solution would be to use an #ifdef. But a more cleaner solution would be to move the most of the code to a base class and create version specific classes (Oxyplot.GtkSharp2, Oxyplot.GtkSharp3).

**Comment by sevoku** [comment]
I've pushed a WIP branch to github at https://github.com/sevoku/oxyplot/tree/add-gtk3-support (to see the changes without #527): https://github.com/sevoku/oxyplot/compare/fix-gtk-targetfw...sevoku:add-gtk3-support). The important commit is bfe0408995ee23136f67a2ab773d0075c5156a81.

Description:
* I've added an OxyPlot.GtkSharp3 project and solution (incl. Gtk3 ExampleBrowser and Demo)
* Gtk2 and Gtk3 share the same Namespace ```Oxyplot.GtkSharp```. This is good for two reasons:
  1. It is not possible to target Gtk2 and Gtk3 at the same time, so there is no reason for separate namespaces. If the user wants to support both versions in one assembly, he/she is forced to dynamically load the GtkSharp assembly and has to ensure not to initialize both Gtk versions at the same time.
  2. Its easy to switch Gtk versions by simply replacing the reference (using same client code). So supporting both versions needs only project configuration based (and no code) changes.
* Gtk3 handles drawing slightly different. There is a Draw event (instead of Expose) which sets up the cairo context correctly (with clipping etc.). So I've made the PlotView partial (https://github.com/oxyplot/oxyplot/commit/bfe0408995ee23136f67a2ab773d0075c5156a81#diff-e7a1cde5d4bba13c0eae64a43b9529cbR25) and added 2 cs files with version specific implementations (https://github.com/oxyplot/oxyplot/commit/bfe0408995ee23136f67a2ab773d0075c5156a81#diff-0da024ba35c6466044212f263db03c7cR1, https://github.com/oxyplot/oxyplot/commit/bfe0408995ee23136f67a2ab773d0075c5156a81#diff-0fd751062f85e710d2bde53fae764396R1). Both call the ```DrawPlot``` method (https://github.com/oxyplot/oxyplot/commit/bfe0408995ee23136f67a2ab773d0075c5156a81#diff-e7a1cde5d4bba13c0eae64a43b9529cbR419) which previously was the Exposed handler.

I'll add a NET40 version and set up AppVeyor. And the original Gtk code needs some cleanup. Then it'll be ready for a PR. And I had added partial tracker support, but I have to find the folder in my archives... so more to come.

Feel free to test and report!

**Comment by juergenhoetzel** [comment]
Nice! Works for me!
