### ISSUE TITLE
Partial invalidation

### ISSUE THREAD

**Issue by objorke** [oxyplot/oxyplot#65]
**Imported from [http://oxyplot.codeplex.com/workitem/10052](http://oxyplot.codeplex.com/workitem/10052)**

**[objo](http://www.codeplex.com/site/users/view/objo)** 2013-06-08 11:25
Allow partial invalidation of the plots. 

E.g. update only the visible elements of an annotation, axis or series. 

The partial invalidation should not be used when the whole model needs to be updated (e.g. when scaling of axes change). The application should be responsible for detecting this...

See 

<a href="https://oxyplot.codeplex.com/discussions/444229" rel="nofollow">https://oxyplot.codeplex.com/discussions/444229</a>

<a href="https://oxyplot.codeplex.com/discussions/444635" rel="nofollow">https://oxyplot.codeplex.com/discussions/444635</a>

**Comment by cfeltch537** [comment]
Has there been any thought towards this feature? I'm attempting to get OxyPlot to works as a robotics mapping solution, but i need to constantly display a bitmap, which updates around 20-30 Hz. Currently I am using an annotation to hold the bitmap, and the software works very well, with the exception of updating the background annotation, which is too laggy . If there were an object 'BackgroundAnnotation' that could be optimized to render quickly, it would be a great feature. Great product otherwise.

**Comment by objorke** [comment]
This issue is marked "wont-fix", and I still think the cost-benefit is not good enough to do this. But if someone sees a way to solve this easily, it would be great to see it happen!

@cfeltch537 I think the performance of the bitmap conversion/rendering should be a new issue. I don't think this code has been profiled, and it is very possible that something can be improved!
