### ISSUE TITLE
Deep copy of PlotModel

### ISSUE THREAD

**Issue by icypixels** [oxyplot/oxyplot#666]
Hello everyone,

I just recently started using OxyPlot so please excuse me if this is a beginner question. I'm using OxyPlot in a WPF application and I need to somehow perform a deep copy of the PlotModel, in order to later reuse some components from the model in a new one.
Basically, with each new PlotModel, I want to take all the Series from the previous ones and add some more. Any suggestions?

Thank you for your time!

**Comment by objorke** [comment]
I don't think we should support copy/clone of plot models. I think it would be better if you rebuild the model in your code. Please add comments if  you disagree.

**Comment by icypixels** [comment]
I agree, I managed to get it done in my own code. And it won't be ever needed if the possibility to have more views for a PlotModel will be implemented ( #497 ).

**Comment by objorke** [comment]
Good, then I'll close this issue.

**Comment by Fellfalla** [comment]
I've got a PlotViewRenderer for UWP to be able to use UWP plots with Xamarin Forms. And there is the need to transfer the Model from the OxyPlot.Xamarin.Forms.PlotView class into a OxyPlot.Windows.PlotView in order to show it. However, oxyplot doesn't let me referencing the existing model, so I have to do something like a copy.

**Comment by anuviswan** [comment]
I was wondering if the possibility of PlotModel Clone is still open ? I was working on a scenario where I was building the basic Plot Model and then having few 'decorators' add features to it at different stage. At the same time, I would like to implement some sort of memento which will keep track state of plot model at different stages. However lack of Clone is effecting me. Is there a workaround or do you think Clone is still open for discussion

**Comment by hammondreg** [comment]
There is a definite need for a PlotModel Copy or Clone facility/ability.  I have an Xamarin forms project and I can show OxyPlot PlotViews with a model attached.  Now I click on the PlotModel in order to see a bigger view in a popup.  Di I really have to do ALL the calculations and computations I have already done in order to create a 'copy' of my existing PlotModel to see in the popup??  Really??!??

**Comment by igitur** [comment]
Since v2.1 `PngExporter` doesn't have an explicit `Background` property anymore and we're expected to use `PlotModel.Background`. I want a transparent background in my WPF application, but when exporting to .png, I don't want a white background. I don't want to modify the plot model temporarily while exporting and then have to revert it back. This is a perfect use case of where a deep clone is needed.

**Comment by dragongling** [comment]
I have the same issue as @igitur , I need to clone `PlotModel` because I want to export the model to image differently than it's displayed in my WPF app.

**Comment by Spordoz** [comment]
Same here, I would like to allow the user to change some settings to alter the way the plot is displayed before exporting it to an image, but I don't want to change my existing plot in the process.
