### ISSUE TITLE
Add support for Xamarin.Forms UWP

### ISSUE THREAD

**Issue by choenden** [oxyplot/oxyplot#697]
With xamarin.forms, I created a UWP application. When the nugget package for OxyPlot is added, there is no Platform.UWP for which I could call this initialization method:
OxyPlot.Xamarin.Forms.Platform.UWP.PlotViewRenderer.Init();

I'm not yet sure whether I missed something or whether this really is the case. Looking at the source code, there only seems to be a win8/wp8 project. I made a small local fork where I modified the win8 project to use the UWP platform instead.

**Comment by choenden** [comment]
Sorry, turns out this is a duplicate of #615

**Comment by objorke** [comment]
No, I think this is a valid issue. In my opinion, #615 does not include support for Xamarin.Forms

**Comment by objorke** [comment]
https://developer.xamarin.com/guides/xamarin-forms/windows/getting-started/universal/
Only available in preview yet?

**Comment by tibel** [comment]
Also related to #461

**Comment by choenden** [comment]
Cool, @tibel @objorke can I take this then? I've been meaning to contribute to something opensource for a while. UWP is available in the released xamarin forms 2.0 but it is in the preview phase.

**Comment by objorke** [comment]
You are very welcome to take this task! I'll assign it to you.
I think #615 is a prerequisite, I have run into some build problems on this, see https://github.com/oxyplot/oxyplot/pull/616

**Comment by choenden** [comment]
Thanks @objorke . I have created the UWP project and it seems to work fine with my own example project. I expanded the SimpleDemo to also have a UWP target, but there I am getting this exception. Is this a known issue or do you have any advice?
		Message	"Cannot deserialize XBF metadata type list as 'ThicknessConverter' was not found in namespace 'OxyPlot.Windows'. [Line: 0 Position: 0]"	string

**Comment by choenden** [comment]
Ah. Forgot to reference that assembly in the sample project -_-

**Comment by andrii-borysov-me** [comment]
Hi guys. It seems we're still missing the support on nuget. Any update or expectation, when we'll be happy to have it? Thanks.

**Comment by dimitrijevic** [comment]
Hi guys. I know that support OxyPlot.Windows in Xamarin.Forms has been marked closed, but has anyone here had a problem building an x86/ARM Release project and not having the plot show up? I was getting this previously in Release builds of even SimpleDemo.UWP project, but since I've updated to the newest Windows 10 Insider build and also Xamarin.Forms referenced 2.2 so I'm getting it in Debug... The PlotRendered Init call gets called, and I've tried adding all assemblies and directives I could think of since it looked previously like a .NET Native tool chain build optimization problem, but now I just don't know what's the problem, maybe it's just my machine!? TIA

**Comment by clarkis117** [comment]
I'm not seeing support for this either on Nuget, are there any blocking issues that I can help address?

**Comment by objorke** [comment]
The Xamarin projects are moved to another repository, and there is a new issue for this https://github.com/oxyplot/oxyplot-xamarin/issues/16
