### ISSUE TITLE
AreaSeries throws NullReferenceException

### ISSUE THREAD

**Issue by GeertvanHorrik** [oxyplot/oxyplot#784]
When working on examples for the animations, the AreaSeries throws an exception (but can continue to display data):

![image](https://cloud.githubusercontent.com/assets/1246444/13173388/7d6a0ba6-d6fd-11e5-95c7-166bff8f535f.png)

I think a (actualPoints == null || actualPoints.Count == 0) solves this.

**Comment by objorke** [comment]
could this be due to a race condition in your code? are you updating the plot model and redrawing at the same time?

we have had some similar issues, and I think it is ok to make this consistent with LineSeries:
https://github.com/oxyplot/oxyplot/blob/develop/Source/OxyPlot/Series/LineSeries.cs#L327

**Comment by GeertvanHorrik** [comment]
It's when running the animations demo (which I just copy/pasted from another example).

**Comment by GeertvanHorrik** [comment]
I will create a PR.
