### ISSUE TITLE
MinimumMajorStep and MinimumMinorStep for Oxyplot.Axes.Axis

### ISSUE THREAD

**Issue by Jonarw** [oxyplot/oxyplot#816]
For some kinds of plots, it it undesirable to have arbitrarily small grid line steps. 

In my particular case, I want a stem plot of a discrete-time acoustical impulse response. This type of function is only defined at integer time samples and therefore the plot should not have gridlines at fractions (see attached files for comparison).
Using a fixed step size (with MajorStep and MinorStep) is impractical, as the plot should also work for more than a few samples.

Implementation is done and tested, just waiting for you-take-it :)

![1](https://cloud.githubusercontent.com/assets/18097859/14065186/63423b8c-f420-11e5-9c3a-d91e718e7004.png)
![2](https://cloud.githubusercontent.com/assets/18097859/14065187/6343aada-f420-11e5-9570-aefe25c910f0.png)

**Comment by objorke** [comment]
How will you solve this? Add `MinimumMajorStep` and `MinimumMinorStep` properties?

**Comment by Jonarw** [comment]
Yes, exactly. Then I'd enforce those minimums in Axis.UpdateIntervals(). If you want you can take a look at Axis.cs in my fork, where this is already implemented.

**Comment by objorke** [comment]
Looks ok to me!

**Comment by raffaeler** [comment]
@Jonarw How did you add the series to draw the vertical line of the pulses with the small circle?
TIA

**Comment by VisualMelon** [comment]
@raffaeler it is a [`StemSeries`](https://github.com/oxyplot/docs/blob/master/models/series/StemSeries.rst).

**Comment by raffaeler** [comment]
Thank you @VisualMelon 
I continue jumping from the examples to the docs, but I have a very long list of doubts on how does this library work.

**Comment by raffaeler** [comment]
BTW, I still can't find a way to repro the images above.
Yes, I am new to this library. Yes, I tried the examples, Yes, I read the docs.
Sorry for bothering.

**Comment by VisualMelon** [comment]
Which part in particular is problematic? Can you provide your code and a screenshot?

`StemSeries` is a `DataPointSeries`, so you just feed the `Points` property (or `ItemSource`). Each point becomes a stem. By default there is no blob on the end: you need to specify the `StemSeries.MarkerType` (e.g. `MarkerType.Circle`) and `StemSeries.MarkerFill`. The marker fill feels wrong TBH... it's Automatic by default, which I'd expect to mean it is the same as the stem.

There is another example for `StemSeries` here: https://github.com/oxyplot/oxyplot/blob/develop/Source/Examples/ExampleLibrary/Series/StemSeriesExamples.cs

**Comment by VisualMelon** [comment]
Yeah, that looks like a bug.

**Comment by VisualMelon** [comment]
@raffaeler opened #1630

**Comment by raffaeler** [comment]
Thank you @VisualMelon I didn't have much time yet to experiment all the properties, but I believe to have found what I was looking for.
BTW while I totally appreciate the efforts in this project, let me give a constructive feedback (at least I hope so):
- The samples aren't of great help because the info are sparse. Personally I would prefer separate samples even if they would require a lot of boilerplate code to be repeated.
- The WPF samples show to either use PlotView or Plot, but isn't clear what are the pros/cons of the two.
- Instead of spending time in documenting every single property (which will require a huge amount of time), I would focus more on the "rationale" and use-cases

**Comment by VisualMelon** [comment]
@raffaeler could you elaborate on that first bullet point? I'm not sure what you mean.

**Comment by raffaeler** [comment]
@VisualMelon take for example the StemSeries link. It just fill out a number of properties on a class. It is useful to discover, for example, `MarkerType` but not really to discover the class itself or how to use it when the view uses a Plot and not a PlotView/PlotModel. End-to-end examples are really not good-looking but more informative.
The current ramp to understand how the library work could be improved IMO.

**Comment by VisualMelon** [comment]
OK. I have almost no imagination, but if I'm understanding what you are saying:
 - It is hard to identity which series/features you need (because there are so many examples, only the maintainers have the energy to search through them all)
 - It is hard to find complete examples on a per-platform basis, because all the examples just create a `PlotModel` (though this is the idea: it should be no effort to set up the `PlotView`; the `PlotModel` is the main concern).

With regard to `Plot`/`PlotView`, I have hardly used the WPF provision, but basically you use a `PlotView` to present a `PlotModel`. `Plot` is for XAML defined plots, and is now in [oxyplot-contib](https://github.com/oxyplot/oxyplot-contrib) I think, so the docs are out of date, but the `WPF` vs `WPF - XAML` 'Create Project' pages show the usage: https://oxyplot.readthedocs.io/en/latest/getting-started/hello-wpf.html ; https://oxyplot.readthedocs.io/en/latest/getting-started/hello-wpf-xaml.html

The docs generally need updating and improving. This discussion should probably be over at https://github.com/oxyplot/docs so it doesn't get lost.

**Comment by raffaeler** [comment]
I believe that your last comment should go in the docs. It is definitely precious to understand the objects to start using and the pros/cons of the different solutions.

I use WPF with my own MVVM framework, therefore any solution allowing to bind the data I want to plot is good. I have seen a couple of posts on StackOverflow showing how to animate real-time data. I would suggest to include those kind of suggestions in the docs as well.

I am currently trying to build a small app showing a sort of step-by-step solution to a problem. Every step modify the series and update the results. Should be very simple but I can't spend much time on it, it is just an experiment.

Thanks for your help
